### ISSUE TITLE
Potential refactors and bugfixes for Day 1 Part 1

### ISSUE THREAD

**Issue by internet-diglett** [nathanhitchcock/advent_of_code_2021#1]
https://github.com/nathanhitchcock/advent_of_code_2021/blob/cf52f92e2ec6598f83e0dff61f18523cb100ccef/day1/main.py#L7-L16

This code could be simplified to

```python
lst = open("input.dat").readlines()
```

Another thing to consider is that your numbers will be read in from the file as Strings, not Integers. Comparing strings will lead to unexpected results, for example:

```python
$ ipython 
Python 3.9.4 (default, Apr  7 2021, 19:20:43)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.22.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: "10" > "12"
Out[1]: False

In [2]: "10" > "2"
Out[2]: False

In [3]: 10 > 2
Out[3]: True
```
When comparing strings, python compares alphabetical order of each character (1 is less than 2, therefore whatever comes after 1 is irrelevant).

You'll need to convert your strings to integers before or during the comparison to get the expected behavior.

**Comment by nathanhitchcock** [comment]
thank you! 

I've simplified the file reading and changed the comparison to integers and am now getting the expected result! the 'off by one' was throwing me off on this one.  

much appreciated!
